Chore/add registration user to download data tests
uc-cdis/gen3-qa pull request #708
Opened 2021-09-28 17:40 UTC by jingh8

Jira Ticket: https://ctds-planx.atlassian.net/browse/PXP-8692
Add automation tests for Register MIDRC Users for Registered Data Downloading

2021-09-28 17:46 UTC, themarcelor commented on codecept.conf.js
> +    FileSystem: {},
that is not compatible with Webdriver 😢

2021-09-28 17:49 UTC, themarcelor approved these changes
+1

2021-09-28 21:57 UTC, rnerella92 requested changes
The terms and conditions part is still in discussion state. I will finalize the feature doc and let you know. Please comment this part until code is in master

2021-11-08 13:53 UTC, rnerella92 approved these changes

2021-11-08 15:50 UTC, merged